name: "Pull request validation"
on: pull_request

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install python
              uses: actions/setup-python@v1
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install setuptools wheel twine flake8

            - name: Build package and push on pypi
              run: |
                # Get started
                python setup.py sdist bdist_wheel
                twine check dist/*

            - name: Run flake8
              uses: suo/flake8-github-action@releases/v1
              with:
                  checkName: 'validate'   # NOTE: this needs to be the same as the job name
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
